In [1]:
import pandas as pd
import numpy as np
import re
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt

train = pd.read_csv("cs-training.csv")

In [2]:
train.shape

(150000, 12)

In [3]:
train.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,75000.500000,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,43301.414527,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,112500.250000,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,150000.000000,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [5]:
# train['MonthlyIncome'].fillna(train['MonthlyIncome'].median(), inplace=True)
# train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         150000 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [6]:
# train['NumberOfDependents'].fillna(train['NumberOfDependents'].median(), inplace=True)
# train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         150000 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    150000 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [5]:
from collections import Counter
def detect_outliers(df,n,features):
    outlier_indices = []
    
    # iterate over features(columns)
    for col in features:
        # 1st quartile (25%)
        Q1 = np.percentile(df[col], 25)
        # 3rd quartile (75%)
        Q3 = np.percentile(df[col],75)
        # Interquartile range (IQR)
        IQR = Q3 - Q1
        
        # outlier step
        outlier_step = 1.5 * IQR
        
        # Determine a list of indices of outliers for feature col
        outlier_list_col = df[(df[col] < Q1 - outlier_step) | (df[col] > Q3 + outlier_step )].index
        
        # append the found outlier indices for col to the list of outlier indices 
        outlier_indices.extend(outlier_list_col)
        
    # select observations containing more than 2 outliers
    outlier_indices = Counter(outlier_indices)        
    multiple_outliers = list( k for k, v in outlier_indices.items() if v > n )
    
    return multiple_outliers

# detect outliers from Age, SibSp , Parch and Fare
# These are the numerical features present in the dataset
Outliers_to_drop = detect_outliers(train,2,["RevolvingUtilizationOfUnsecuredLines",
                                            "age",
                                            "NumberOfTime30-59DaysPastDueNotWorse",
                                            "DebtRatio",
                                            "MonthlyIncome",
                                            "NumberOfOpenCreditLinesAndLoans",
                                            "NumberOfTimes90DaysLate",
                                            "NumberRealEstateLoansOrLines",
                                            "NumberOfTime60-89DaysPastDueNotWorse",
                                            "Unnamed: 0",
                                            "NumberOfDependents"])

In [6]:
train.loc[Outliers_to_drop]

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
900,901,0,2.258964,33,2,0.032484,2000.0,1,1,0,0,2.0
919,920,1,1.362142,73,1,274.000000,NaN,2,3,0,1,NaN
1958,1959,0,1.634551,28,0,151.000000,NaN,1,3,0,2,0.0
4852,4853,0,1.566866,46,2,0.104983,6000.0,3,2,0,0,0.0
5956,5957,0,2.237856,60,6,2597.000000,1.0,16,1,2,1,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
117338,117339,1,0.960692,42,0,1.241580,3770.0,29,1,2,1,3.0
126682,126683,1,0.344297,38,0,1.789158,4500.0,23,14,11,1,0.0
129570,129571,0,0.075067,58,0,0.298925,17388.0,24,0,6,1,0.0
5833,5834,1,0.917527,44,0,1.852144,3800.0,13,1,7,1,1.0
142226,142227,1,0.859714,55,0,0.599348,11046.0,18,7,6,6,1.0

In [7]:
train = train.drop(Outliers_to_drop, axis = 0).reset_index(drop=True)

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146473 entries, 0 to 146472
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            146473 non-null  int64
 1   SeriousDlqin2yrs                      146473 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  146473 non-null  float64
 3   age                                   146473 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  146473 non-null  int64
 5   DebtRatio                             146473 non-null  float64
 6   MonthlyIncome                         118224 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       146473 non-null  int64
 8   NumberOfTimes90DaysLate               146473 non-null  int64
 9   NumberRealEstateLoansOrLines          146473 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  146473 non-null  int64
 11  NumberOfDependents                    142707 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.4 MB

In [29]:
def getIVandWOE(filter):
    current_bin = train[filter].unique().sort_values(ascending=True)
    print(current_bin)
    
    good = train.loc[train['SeriousDlqin2yrs'] == 0].groupby(filter).agg({'SeriousDlqin2yrs': ['count']}).apply(list)
    good_list = good.to_numpy()

    countGood = []
    sumGood = 0

    for i in range (0,len(good_list)-1):
        countGood.append(good_list[i][0])
        sumGood += good_list[i]

    print(countGood)
    # print(sumGood)

    #################################################################################################################

    bad = train.loc[train['SeriousDlqin2yrs'] == 1].groupby(filter).agg({'SeriousDlqin2yrs': ['count']}).apply(list)
    bad_list = bad.to_numpy()

    countBad = []
    sumBad = 0;

    for i in range (0,len(bad_list)-1):
        countBad.append(bad_list[i][0])
        sumBad += bad_list[i]

    print(countBad)
    # print(sumBad)

    total=[]
    badRate=[]
    badPercentage=[]
    goodPercentage = []
    quotient =[]
    diff=[]
    woe=[]

    for i in range(0,len(good_list)-1):
        total.append(countGood[i]+countBad[i])
        badRate.append(countBad[i]/total[i])
        badPercentage.append(countBad[i]/sumBad)
        goodPercentage.append(countGood[i]/sumGood)
        
        if(badPercentage[i] == 0):
            quotient.append(0)
        else:    
            quotient.append(goodPercentage[i]/badPercentage[i])
        
        diff.append(goodPercentage[i]-badPercentage[i])
        
        if(quotient[i]==0):
            woe.append(0)
        else:
            woe.append((np.log(quotient[i]))*100)

    # bad = train.loc[train['SeriousDlqin2yrs'] == 1].groupby('age_bin').agg({'SeriousDlqin2yrs': ['count']})
    # print(bad)

    # count_bin_age = train.groupby('age_bin').agg({'SeriousDlqin2yrs': ['count']})
    # print(count_bin_age)

    iv = 0;

    for i in range(0,len(good_list)-1):
        if(diff[i]!=0 and quotient[i]!=0):
            iv += (diff[i]*(np.log(quotient[i])))

    print("IV: ",iv)

    data = pd.DataFrame()
    data.insert(0,filter,current_bin)
    data.insert(1,'good',countGood)
    data.insert(2,'bad',countBad)
    data.insert(3,'total_count',total)
    data.insert(4,'dist_bad',badPercentage)
    data.insert(5,'dist_good',goodPercentage)
    data.insert(6,'bad_rate',badRate)
    data.insert(7,'quotient',quotient)
    data.insert(8,'difference',diff)
    data.insert(9,'WoE',woe)
    display(data)
    return iv

In [21]:
print("Max age: ", train['age'].max())
print("Min age: ", train['age'].min())

train['age_bin'] = pd.cut(train['age'], bins = [0,10,20,30,40,50,60,70,80,90,100,110])
train.head()

Max age:  109
Min age:  0

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,age_bin,income_bin,debt_bin
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,"(40, 50]","(0, 100000]","(0, 20000]"
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,"(30, 40]","(0, 100000]","(0, 20000]"
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,"(30, 40]","(0, 100000]","(0, 20000]"
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,"(20, 30]","(0, 100000]","(0, 20000]"
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,"(40, 50]","(0, 100000]","(0, 20000]"

In [22]:
age_iv = getIVandWOE('age_bin')
print(age_iv)

[(20.0, 30.0], (30.0, 40.0], (40.0, 50.0], (50.0, 60.0], (60.0, 70.0], (70.0, 80.0], (80.0, 90.0], (90.0, 100.0], (100.0, 110.0], NaN]
Categories (9, interval[int64]): [(20, 30] < (30, 40] < (40, 50] < (50, 60] ... (70, 80] < (80, 90] < (90, 100] < (100, 110]]
[0, 0, 9312, 21630, 31690, 32203, 26201, 12330, 4335, 462]
[0, 0, 1048, 1988, 2382, 1752, 785, 259, 76, 6]
IV:  [0.24587752]

<ipython-input-20-617cc87a71fd>:43: RuntimeWarning: invalid value encountered in longlong_scalars
  badRate.append(countBad[i]/total[i])

,age_bin,good,bad,total_count,dist_bad,dist_good,bad_rate,quotient,difference,WoE
0,"(20.0, 30.0]",0,0,0,[0.0],[0.0],NaN,0,[0.0],0
1,"(30.0, 40.0]",0,0,0,[0.0],[0.0],NaN,0,[0.0],0
2,"(40.0, 50.0]",9312,1048,10360,[0.12632594021215043],[0.06739865231646679],0.101158,[0.5335297897112676],[-0.05892728789568365],[-62.82403715400557]
3,"(50.0, 60.0]",21630,1988,23618,[0.23963355834136935],[0.1565542149490095],0.084173,[0.6533067239522047],[-0.08307934339235984],[-42.57085448997023]
4,"(60.0, 70.0]",31690,2382,34072,[0.28712632594021215],[0.22936676244725432],0.069911,[0.7988357100178094],[-0.05775956349295783],[-22.45999738605664]
5,"(70.0, 80.0]",32203,1752,33955,[0.2111861137897782],[0.23307976809999784],0.051598,[1.1036699521447386],[0.02189365431021964],[9.864094676789811]
6,"(80.0, 90.0]",26201,785,26986,[0.09462391513982642],[0.1896383257456772],0.029089,[2.00412681577852],[0.0950144106058508],[69.52084625470465]
7,"(90.0, 100.0]",12330,259,12589,[0.031219864995178398],[0.08924241656594023],0.020574,[2.858513852629499],[0.05802255157076183],[105.03018578285648]
8,"(100.0, 110.0]",4335,76,4411,[0.009161041465766635],[0.031375983439850035],0.017230,[3.4249362975920508],[0.0222149419740834],[123.10828722980236]
9,NaN,462,6,468,[0.0007232401157184186],[0.0033438764358040864],0.012821,[4.62346648523845],[0.002620636320085668],[153.11447452233963]

[0.24587752]

In [12]:
print("Max income: ", train['MonthlyIncome'].max())
print("Min income: ", train['MonthlyIncome'].min())


train['income_bin'] = pd.cut(train['MonthlyIncome'], bins = [0,100000,200000,300000,400000,500000,600000,700000,800000,900000,1000000,2000000,3000000])
train.head()

Max income:  3008750.0
Min income:  0.0

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,age_bin,income_bin
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,"(40, 50]","(0, 100000]"
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,"(30, 40]","(0, 100000]"
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,"(30, 40]","(0, 100000]"
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,"(20, 30]","(0, 100000]"
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,"(40, 50]","(0, 100000]"

In [13]:
income_iv = getIVandWOE('income_bin')
print(income_iv)

[(0, 100000], (100000, 200000], (200000, 300000], (300000, 400000], (400000, 500000], ..., (600000.0, 700000.0], (700000.0, 800000.0], (800000.0, 900000.0], (1000000.0, 2000000.0], NaN]
Length: 11
Categories (10, interval[int64]): [(0, 100000] < (100000, 200000] < (200000, 300000] < (300000, 400000] ... (600000, 700000] < (700000, 800000] < (800000, 900000] < (1000000, 2000000]]
[109358, 38, 10, 2, 3, 2, 3, 2, 1, 0, 3]
[7228, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
IV:  [0.00021192]

<ipython-input-9-617cc87a71fd>:43: RuntimeWarning: invalid value encountered in longlong_scalars
  badRate.append(countBad[i]/total[i])

,income_bin,good,bad,total_count,dist_bad,dist_good,bad_rate,quotient,difference,WoE
0,"(0.0, 100000.0]",109358,7228,116586,[0.9997233748271093],[0.9994151084790993],0.061997,[0.9996916483541627],[-0.00030826634800995567],[-0.03083991959810858]
1,"(100000.0, 200000.0]",38,1,39,[0.00013831258644536652],[0.0003472793405348102],0.025641,[2.510829632066678],[0.00020896675408944366],[92.0613229234309]
2,"(200000.0, 300000.0]",10,1,11,[0.00013831258644536652],[9.138930014073952e-05],0.090909,[0.6607446400175467],[-4.6923286304627004e-05],[-41.438783749803115]
3,"(300000.0, 400000.0]",2,0,2,[0.0],[1.8277860028147905e-05],0.000000,0,[1.8277860028147905e-05],0
4,"(400000.0, 500000.0]",3,0,3,[0.0],[2.7416790042221856e-05],0.000000,0,[2.7416790042221856e-05],0
5,"(500000.0, 600000.0]",2,0,2,[0.0],[1.8277860028147905e-05],0.000000,0,[1.8277860028147905e-05],0
6,"(600000.0, 700000.0]",3,0,3,[0.0],[2.7416790042221856e-05],0.000000,0,[2.7416790042221856e-05],0
7,"(700000.0, 800000.0]",2,0,2,[0.0],[1.8277860028147905e-05],0.000000,0,[1.8277860028147905e-05],0
8,"(800000.0, 900000.0]",1,0,1,[0.0],[9.138930014073952e-06],0.000000,0,[9.138930014073952e-06],0
9,"(1000000.0, 2000000.0]",0,0,0,[0.0],[0.0],NaN,0,[0.0],0
10,NaN,3,0,3,[0.0],[2.7416790042221856e-05],0.000000,0,[2.7416790042221856e-05],0

[0.00021192]

In [15]:
print("Max Debt Ratio: ", train['DebtRatio'].max())
print("Min Debt Ratio: ", train['DebtRatio'].min())

train['debt_bin'] = pd.cut(train['DebtRatio'], bins = [0,20000,40000,60000,80000,100000,120000,140000,160000,180000,200000,220000,240000,260000,280000,300000])
train.head()

Max Debt Ratio:  329664.0
Min Debt Ratio:  0.0

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,age_bin,income_bin,debt_bin
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,"(40, 50]","(0, 100000]","(0, 20000]"
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,"(30, 40]","(0, 100000]","(0, 20000]"
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,"(30, 40]","(0, 100000]","(0, 20000]"
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,"(20, 30]","(0, 100000]","(0, 20000]"
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,"(40, 50]","(0, 100000]","(0, 20000]"

In [16]:
debt_iv = getIVandWOE('debt_bin')
print(debt_iv)

[(0.0, 20000.0], (20000.0, 40000.0], (40000.0, 60000.0], (60000.0, 80000.0], (100000.0, 120000.0], (160000.0, 180000.0], (220000.0, 240000.0], NaN]
Categories (7, interval[int64]): [(0, 20000] < (20000, 40000] < (40000, 60000] < (60000, 80000] < (100000, 120000] < (160000, 180000] < (220000, 240000]]
[134486, 16, 4, 3, 0, 3, 0, 0, 1, 0, 0, 1, 0, 0]
[8059, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
IV:  [2.23077837e-07]

<ipython-input-9-617cc87a71fd>:43: RuntimeWarning: invalid value encountered in longlong_scalars
  badRate.append(countBad[i]/total[i])

ValueError: Length of values (14) does not match length of index (8)

In [18]:
print("Max Unsecured Lines: ", train['RevolvingUtilizationOfUnsecuredLines'].max())
print("Min Unsecured Lines: ", train['RevolvingUtilizationOfUnsecuredLines'].min())

train['unsecured_bin'] = pd.cut(train['RevolvingUtilizationOfUnsecuredLines'], bins = [0,10000,20000,30000,40000,50000])
train.head()

Max Unsecured Lines:  50708.0
Min Unsecured Lines:  0.0

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,age_bin,income_bin,debt_bin,unsecured_bin
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,"(40, 50]","(0, 100000]","(0, 20000]","(0, 10000]"
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,"(30, 40]","(0, 100000]","(0, 20000]","(0, 10000]"
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,"(30, 40]","(0, 100000]","(0, 20000]","(0, 10000]"
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,"(20, 30]","(0, 100000]","(0, 20000]","(0, 10000]"
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,"(40, 50]","(0, 100000]","(0, 20000]","(0, 10000]"

In [19]:
unsecured_iv = getIVandWOE('unsecured_bin')
print(unsecured_iv)

[(0.0, 10000.0], (10000.0, 20000.0], (20000.0, 30000.0], NaN]
Categories (3, interval[int64]): [(0, 10000] < (10000, 20000] < (20000, 30000]]
[126443, 8, 4, 0]
[7628, 0, 0, 0]
IV:  [9.00556753e-09]

<ipython-input-11-617cc87a71fd>:43: RuntimeWarning: invalid value encountered in longlong_scalars
  badRate.append(countBad[i]/total[i])

,unsecured_bin,good,bad,total_count,dist_bad,dist_good,bad_rate,quotient,difference,WoE
0,"(0.0, 10000.0]",126443,7628,134071,[1.0],[0.9999051045826579],0.056895,[0.9999051045826579],[-9.489541734208906e-05],[-0.009489992019707445]
1,"(10000.0, 20000.0]",8,0,8,[0.0],[6.326361156142502e-05],0.000000,0,[6.326361156142502e-05],0
2,"(20000.0, 30000.0]",4,0,4,[0.0],[3.163180578071251e-05],0.000000,0,[3.163180578071251e-05],0
3,NaN,0,0,0,[0.0],[0.0],NaN,0,[0.0],0

[9.00556753e-09]

In [27]:
print("Max # of times 30-59 Days Past Due: ", train['NumberOfTime30-59DaysPastDueNotWorse'].max())
print("Min # of times 30-59 Days Past Due: ", train['NumberOfTime30-59DaysPastDueNotWorse'].min())

train['30to59_days_due_bin'] = pd.cut(train['NumberOfTime30-59DaysPastDueNotWorse'], bins = [0,2,4,6,8,10,12,14])
train.head()

Max # of times 30-59 Days Past Due:  13
Min # of times 30-59 Days Past Due:  0

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,age_bin,income_bin,debt_bin,num_open_credit,30to59_days_due_bin
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,"(40, 50]","(0, 100000]","(0, 20000]","(10, 20]","(0.0, 2.0]"
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,"(30, 40]","(0, 100000]","(0, 20000]","(0, 10]",NaN
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,"(30, 40]","(0, 100000]","(0, 20000]","(0, 10]","(0.0, 2.0]"
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,"(20, 30]","(0, 100000]","(0, 20000]","(0, 10]",NaN
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,"(40, 50]","(0, 100000]","(0, 20000]","(0, 10]","(0.0, 2.0]"

In [28]:
num30to59_days_due_iv = getIVandWOE('30to59_days_due_bin')
print(num30to59_days_due_iv)

[(0.0, 2.0], (2.0, 4.0], (4.0, 6.0], (6.0, 8.0], (8.0, 10.0], (10.0, 12.0], (12.0, 14.0], NaN]
Categories (7, interval[int64]): [(0, 2] < (2, 4] < (4, 6] < (6, 8] < (8, 10] < (10, 12] < (12, 14]]
[15826, 1313, 193, 29, 4, 1]
[2624, 600, 134, 17, 2, 1]
IV:  [0.14938933]

ValueError: Length of values (6) does not match length of index (8)

In [23]:
print("Max # of open credit lines: ", train['NumberOfOpenCreditLinesAndLoans'].max())
print("Min # of open credit lines: ", train['NumberOfOpenCreditLinesAndLoans'].min())

train['num_open_credit'] = pd.cut(train['NumberOfOpenCreditLinesAndLoans'], bins = [0,10,20,30,40,50,60])
train.head()

Max # of open credit lines:  57
Min # of open credit lines:  0

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,age_bin,income_bin,debt_bin,num_open_credit
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,"(40, 50]","(0, 100000]","(0, 20000]","(10, 20]"
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,"(30, 40]","(0, 100000]","(0, 20000]","(0, 10]"
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,"(30, 40]","(0, 100000]","(0, 20000]","(0, 10]"
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,"(20, 30]","(0, 100000]","(0, 20000]","(0, 10]"
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,"(40, 50]","(0, 100000]","(0, 20000]","(0, 10]"

In [24]:
num_open_credit_iv = getIVandWOE('num_open_credit')
print(num_open_credit_iv)

[(0.0, 10.0], (10.0, 20.0], (20.0, 30.0], (30.0, 40.0], (40.0, 50.0], (50.0, 60.0], NaN]
Categories (6, interval[int64]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] < (40, 50] < (50, 60]]
[97210, 36280, 3122, 253, 38]
[5552, 2222, 175, 13, 6]
IV:  [0.00149036]

ValueError: Length of values (5) does not match length of index (7)